environment:
  nodejs_version: '14'

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g markbind-cli
  - markbind build
  - markbind deploy --ci

test: off

build: off
