jobs:
  Build-And-Deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: "16"
          npm-version: "7"
          install-yarn: false
      - run: node --version
      - run: npm i -g markbind-cli
      - run: markbind build
      - run: markbind deploy --ci
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  Deploy-MarkBind-Site:
    jobs:
      - Build-And-Deploy
