name: MarkBind Action

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: yucheng11122017/markbind-action@replaceSetOutput
        with:
          service: 'surge'
          purpose: 'pr-preview'
          version: '4.0.0'
          token: ${{ secrets.SURGE_TOKEN }}
          domain: 'mb-test.surge.sh'
