name: MarkBind Action

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: yucheng11122017/markbind-action@upgradeNode16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 'development'
